# Generated by Django 5.1.1 on 2024-09-17 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_listing_current_bid_alter_bid_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='n_bids',
            field=models.IntegerField(default=0),
        ),
    ]
